### ISSUE TITLE
Replace link to draft standard

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/GeoPoseWeb#27]
Now that the standard has been fully approved, the link to the draft standard should be replaced.

**Comment by MikelSalazar** [comment]
Oh! Sorry, I didn't see this issue before. I'm happy to see you were able to update the site yourself.

**Comment by MikelSalazar** [comment]
Oh! Sorry, I didn't see this issue before. I'm happy to see you were able to update the site yourself.
