### ISSUE TITLE
Scrolling direction

### ISSUE THREAD

**Issue by MikelSalazar** [opengeospatial/GeoPoseWeb#4]
Since in VR there is a limit to the vertical placement of things (without breaking the user's spine), for the WebXR prototype, I placed the different sections horizontally so that they can be accessed by simply moving the camera to the left and right (or looking around with the headset) . However, that goes against the convention of vertical scrolling for navigation in web sites (because the original HTML standard was originally defined to share text documents). Can we use horizontal scrolling+snapping for the normal HTML version of the website? For consistency, more than anything else.

For reference, here is a list of websites that use horizontal scrolling to provide a better user experience.
https://qodeinteractive.com/magazine/horizontal-scrolling-websites/

**Comment by cperey** [comment]
I was unaware of horizontal scrolling. The link to examples of sites that have implemented it is helpful but it doesn't "feel" natural to me! 

I'm concerned that the novelty of horizontal scrolling will inhibit the target users/visitors of the site.

**Comment by janerivi** [comment]
For the sandbox experience I am in favor of horizontal as it makes sense for VR/AR ways of viewing it. For the landing page I think we should be strictly conventional to provide the best possible accesibility and lower the bariers for the people entering the webpage. When you purpusfully enter a spatial experience on the other hand it can make more sense to go for a horizontal experience.

**Comment by MikelSalazar** [comment]
OK. Vertical scrolling it is (at least, for the navigation between main sections). For the WebXR version I'll simply arrange the same sections in an horizontal layout.
